steps:
- name: 'docker/compose:1.19.0'
  args: ['up', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_grafana-server:latest', 'gcr.io/$PROJECT_ID/workspace_grafana-server:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_prometheus-server:latest', 'gcr.io/$PROJECT_ID/workspace_prometheus-server:$COMMIT_SHA']  
images: ['gcr.io/$PROJECT_ID/workspace_grafana-server:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/workspace_prometheus-server:$COMMIT_SHA']