steps:
- name: 'docker/compose:1.19.0'
  args: ['up', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'grafana-server:latest', 'gcr.io/$PROJECT_ID/grafana-server:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/grafana-server:$COMMIT_SHA']